# Generated by Django 6.1.1 on 2026-09-20 08:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام دارایی')),
                ('asset_type', models.CharField(choices=[('bank_account', 'حساب بانکی'), ('cash', 'وجه نقد'), ('gold_fund', 'صندوق طلا'), ('gold', 'طلا'), ('stocks', 'سهام'), ('currency', 'ارز'), ('real_estate', 'ملک'), ('vehicle', 'خودرو'), ('deposit', 'سپرده'), ('crypto', 'رمزارز'), ('other', 'سایر دارایی\u200cها')], db_index=True, default='other', max_length=20, verbose_name='نوع دارایی')),
                ('purchase_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), 'ارزش خرید نمی\u200cتواند منفی باشد.')], verbose_name='ارزش خرید')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خرید')),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, help_text='برای دارایی\u200cهایی مانند صندوق، طلا یا سهام', max_digits=20, null=True, verbose_name='مقدار')),
                ('unit', models.CharField(blank=True, help_text='مثلاً «واحد»، «گرم»، «سهم»', max_length=30, verbose_name='واحد')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='در صورت ثبت مقدار، قیمت هر واحد', max_digits=18, null=True, verbose_name='قیمت واحد')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیح')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('provider', models.CharField(blank=True, max_length=80, verbose_name='مؤسسه / ارائه\u200cدهنده')),
                ('include_in_net_worth', models.BooleanField(default=True, verbose_name='محاسبه در ارزش کل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='accounts.account', verbose_name='حساب مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دارایی',
                'verbose_name_plural': 'دارایی\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssetValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), 'ارزش نمی\u200cتواند منفی باشد.')], verbose_name='ارزش')),
                ('valued_on', models.DateField(db_index=True, verbose_name='تاریخ ارزش\u200cگذاری')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='assets.asset', verbose_name='دارایی')),
            ],
            options={
                'verbose_name': 'ارزش\u200cگذاری',
                'verbose_name_plural': 'ارزش\u200cگذاری\u200cها',
                'ordering': ('-valued_on', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['user', 'asset_type'], name='asset_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['user', 'is_active'], name='asset_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='assetvaluation',
            index=models.Index(fields=['asset', 'valued_on'], name='valuation_asset_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetvaluation',
            constraint=models.UniqueConstraint(fields=('asset', 'valued_on'), name='unique_valuation_per_asset_per_day'),
        ),
    ]
