# Generated by Django 6.1.1 on 2026-09-22 13:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('categories', '0002_initial'),
        ('transactions', '0003_transaction_spending_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='سال شمسی')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='ماه شمسی')),
                ('source_label', models.CharField(blank=True, max_length=120, verbose_name='منبع')),
                ('status', models.CharField(choices=[('draft', 'در حال بررسی'), ('committed', 'ثبت\u200cشده')], default='draft', max_length=12, verbose_name='وضعیت')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('committed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_batches', to='accounts.account', verbose_name='حساب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_batches', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسته پیامک',
                'verbose_name_plural': 'دسته\u200cهای پیامک',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SmsImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(verbose_name='متن پیامک')),
                ('sender', models.CharField(blank=True, max_length=80, verbose_name='فرستنده')),
                ('bank', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='بانک')),
                ('bank_label', models.CharField(blank=True, max_length=80, verbose_name='نام بانک')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, verbose_name='اثر انگشت')),
                ('is_transaction', models.BooleanField(default=True, verbose_name='تراکنش است')),
                ('noise_kind', models.CharField(blank=True, max_length=20, verbose_name='نوع پیام غیرتراکنشی')),
                ('direction', models.CharField(blank=True, choices=[('expense', 'هزینه'), ('income', 'درآمد')], max_length=10, verbose_name='جهت')),
                ('direction_pattern', models.CharField(blank=True, max_length=60, verbose_name='الگوی تشخیص')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='مبلغ')),
                ('amount_unit', models.CharField(blank=True, max_length=10, verbose_name='واحد مبلغ')),
                ('amount_unit_assumed', models.BooleanField(default=False, verbose_name='واحد فرض\u200cشده')),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='موجودی پس از تراکنش')),
                ('balance_label', models.CharField(blank=True, max_length=60, verbose_name='برچسب موجودی')),
                ('occurred_on', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاریخ')),
                ('date_source', models.CharField(blank=True, max_length=12, verbose_name='منبع تاریخ')),
                ('confidence', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=4, verbose_name='اطمینان')),
                ('field_confidence', models.JSONField(blank=True, default=dict, verbose_name='اطمینان هر فیلد')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='چهار رقم آخر کارت')),
                ('merchant', models.CharField(blank=True, max_length=120, verbose_name='پذیرنده')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='هشدارها')),
                ('spending_type', models.CharField(blank=True, default='', max_length=10, verbose_name='نوع هزینه')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیح')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('imported', 'ثبت\u200cشده'), ('skipped', 'رد شده'), ('duplicate', 'تکراری')], default='pending', max_length=12, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_items', to='accounts.account', verbose_name='حساب')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sms.smsimportbatch', verbose_name='دسته')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_items', to='categories.category', verbose_name='دسته\u200cبندی')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_item', to='transactions.transaction', verbose_name='تراکنش ثبت\u200cشده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_items', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'قلم پیامک',
                'verbose_name_plural': 'اقلام پیامک',
                'ordering': ('-occurred_on', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SmsReminderDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='سال شمسی')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='ماه شمسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان بستن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_reminder_dismissals', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بستن یادآور پیامک',
                'verbose_name_plural': 'بستن یادآورهای پیامک',
            },
        ),
        migrations.AddIndex(
            model_name='smsimportbatch',
            index=models.Index(fields=['user', 'period_year', 'period_month'], name='sms_batch_period_idx'),
        ),
        migrations.AddIndex(
            model_name='smsimportitem',
            index=models.Index(fields=['batch', 'status'], name='sms_item_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='smsimportitem',
            index=models.Index(fields=['user', 'fingerprint'], name='sms_item_user_fp_idx'),
        ),
        migrations.AddConstraint(
            model_name='smsimportitem',
            constraint=models.UniqueConstraint(fields=('batch', 'fingerprint'), name='unique_fingerprint_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='smsreminderdismissal',
            constraint=models.UniqueConstraint(fields=('user', 'period_year', 'period_month'), name='unique_sms_reminder_dismissal'),
        ),
    ]
