# Generated by Django 6.1.1 on 2026-09-23 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsAutoImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='فعال')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین بررسی')),
                ('last_check_summary', models.JSONField(blank=True, default=dict, verbose_name='خلاصه آخرین بررسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_auto_import', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دریافت خودکار پیامک',
                'verbose_name_plural': 'دریافت خودکار پیامک',
            },
        ),
    ]
