# Generated by Django 6.1.1 on 2026-09-20 08:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(1, 'نام دسته\u200cبندی نمی\u200cتواند خالی باشد.')], verbose_name='نام')),
                ('kind', models.CharField(choices=[('expense', 'هزینه'), ('income', 'درآمد')], db_index=True, default='expense', max_length=10, verbose_name='نوع')),
                ('icon', models.CharField(default='circle-ellipsis', help_text='نام آیکون از کتابخانه Lucide', max_length=40, verbose_name='آیکون')),
                ('color', models.CharField(choices=[('slate', 'خاکستری'), ('red', 'قرمز'), ('orange', 'نارنجی'), ('amber', 'کهربایی'), ('yellow', 'زرد'), ('lime', 'لیمویی'), ('green', 'سبز'), ('teal', 'فیروزه\u200cای'), ('cyan', 'آبی روشن'), ('blue', 'آبی'), ('indigo', 'نیلی'), ('violet', 'بنفش'), ('purple', 'ارغوانی'), ('pink', 'صورتی'), ('rose', 'گلبهی')], default='slate', max_length=20, verbose_name='رنگ')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ('sort_order', 'name'),
            },
        ),
    ]
