# Generated by Django 6.1.1 on 2026-09-20 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'kind', 'is_active'], name='cat_user_kind_active_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'parent'], name='cat_user_parent_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'kind'), name='unique_category_name_per_user_kind'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('pk', models.F('parent')), _negated=True), name='category_parent_not_self'),
        ),
    ]
