# Generated by Django 6.1.1 on 2026-09-20 08:14

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام برچسب')),
                ('color', models.CharField(default='slate', max_length=20, verbose_name='رنگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('expense', 'هزینه'), ('income', 'درآمد')], db_index=True, max_length=10, verbose_name='نوع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'مبلغ باید بیشتر از صفر باشد.')], verbose_name='مبلغ')),
                ('occurred_on', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='تاریخ')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیح')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ('-occurred_on', '-created_at', '-id'),
            },
        ),
    ]
