# Generated by Django 6.1.1 on 2026-09-20 08:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام حساب')),
                ('account_type', models.CharField(choices=[('bank', 'حساب بانکی'), ('cash', 'کیف پول نقدی'), ('card', 'کارت بانکی'), ('investment', 'حساب سرمایه\u200cگذاری'), ('savings', 'حساب پس\u200cانداز'), ('credit', 'کارت اعتباری'), ('other', 'سایر')], db_index=True, default='bank', max_length=20, verbose_name='نوع حساب')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='موجودی اولیه')),
                ('color', models.CharField(default='slate', max_length=20, verbose_name='رنگ')),
                ('icon', models.CharField(default='wallet', max_length=40, verbose_name='آیکون')),
                ('institution', models.CharField(blank=True, max_length=80, verbose_name='بانک / مؤسسه')),
                ('include_in_total', models.BooleanField(default=True, verbose_name='محاسبه در مجموع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'حساب\u200cها',
                'ordering': ('sort_order', 'name'),
            },
        ),
    ]
