# Generated by Django 6.1.1 on 2026-09-20 08:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='سال')),
                ('month', models.PositiveSmallIntegerField(db_index=True, verbose_name='ماه')),
                ('expected_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='درآمد پیش\u200cبینی\u200cشده')),
                ('savings_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='پس\u200cانداز هدف')),
                ('investment_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='سرمایه\u200cگذاری هدف')),
                ('debt_payment_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='بازپرداخت بدهی هدف')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بودجه',
                'verbose_name_plural': 'بودجه\u200cها',
                'ordering': ('-year', '-month'),
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), 'مبلغ بودجه نمی\u200cتواند منفی باشد.')], verbose_name='مبلغ بودجه')),
                ('is_essential', models.BooleanField(default=False, verbose_name='هزینه ضروری')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budgets.budget', verbose_name='بودجه')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='categories.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'ردیف بودجه',
                'verbose_name_plural': 'ردیف\u200cهای بودجه',
                'ordering': ('-amount',),
            },
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'year', 'month'], name='budget_user_ym_idx'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'year', 'month'), name='unique_budget_per_user_month'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='budget_month_in_range'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['budget', 'category'], name='bitem_budget_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetitem',
            constraint=models.UniqueConstraint(fields=('budget', 'category'), name='unique_budget_item_per_category'),
        ),
    ]
