# Generated by Django 6.1.1 on 2026-09-20 08:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('payable', 'بدهی من'), ('receivable', 'طلب من')], db_index=True, default='payable', max_length=12, verbose_name='جهت')),
                ('counterparty', models.CharField(max_length=120, verbose_name='طرف حساب')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'مبلغ باید بیشتر از صفر باشد.')], verbose_name='مبلغ کل')),
                ('issued_on', models.DateField(blank=True, null=True, verbose_name='تاریخ ایجاد')),
                ('due_on', models.DateField(blank=True, db_index=True, help_text='تاریخ سررسید (میلادی ذخیره می\u200cشود، در رابط کاربری شمسی نمایش داده می\u200cشود)', null=True, verbose_name='سررسید')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیح')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تسویه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='accounts.account', verbose_name='حساب مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بدهی / طلب',
                'verbose_name_plural': 'بدهی\u200cها و طلب\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'مبلغ پرداخت باید بیشتر از صفر باشد.')], verbose_name='مبلغ پرداخت')),
                ('paid_on', models.DateField(db_index=True, verbose_name='تاریخ پرداخت')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_payments', to='accounts.account', verbose_name='حساب')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='debts.debt', verbose_name='بدهی')),
            ],
            options={
                'verbose_name': 'پرداخت بدهی',
                'verbose_name_plural': 'پرداخت\u200cهای بدهی',
                'ordering': ('-paid_on', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['user', 'direction', 'settled_at'], name='debt_user_dir_settled_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['user', 'due_on'], name='debt_user_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(condition=models.Q(('principal__gt', 0)), name='debt_principal_positive'),
        ),
        migrations.AddIndex(
            model_name='debtpayment',
            index=models.Index(fields=['debt', 'paid_on'], name='debtpay_debt_date_idx'),
        ),
    ]
